name: signtalk
description: "A new Flutter project."

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  firebase_storage: ^12.4.8
  cloud_firestore: ^5.6.10
  image_picker: ^1.1.2
  google_sign_in: ^5.4.4
  provider: ^6.1.5
  cloud_functions: ^5.6.0
  http: ^1.4.0
  path: ^1.9.1
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^17.2.2
  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/settings_icons/
    - assets/icons/receiver_profile_icons/
    - key.env
